version: '2'

services:
  server:
    build: .
    ports:
      - "10051:10051"
    links:
      - mysql:database
    environment:
      - DB_HOST=database
      - DB_USER=zabbix-user
      - DB_PASSWORD=notsecure
      - DB_NAME=zabbix-db
  web:
    image: simonswine/zabbix-web
    links:
      - mysql:database
      - server:zabbix
    environment:
      - DB_HOST=database
      - DB_USER=zabbix-user
      - DB_PASSWORD=notsecure
      - DB_NAME=zabbix-db
    ports:
      - "8080:80"
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_USER=zabbix-user
      - MYSQL_DATABASE=zabbix-db
      - MYSQL_PASSWORD=notsecure
